apiVersion: apps/v1
kind: Deployment
metadata:
  name: jaeger
  namespace: shoptech
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jaeger
  template:
    metadata:
      labels:
        app: jaeger
    spec:
      containers:
        - name: jaeger
          image: jaegertracing/all-in-one:1.62
          env:
            - name: COLLECTOR_OTLP_ENABLED
              value: "true"
            - name: SPAN_STORAGE_TYPE
              value: memory
            - name: MEMORY_MAX_TRACES
              value: "50000"
          ports:
            - containerPort: 16686  # UI
              name: ui
            - containerPort: 4317   # OTLP gRPC (recibe del collector)
              name: otlp-grpc
            - containerPort: 4318   # OTLP HTTP
              name: otlp-http
          readinessProbe:
            httpGet:
              path: /
              port: 16686
            initialDelaySeconds: 5
            periodSeconds: 10
          resources:
            requests:
              cpu: 100m
              memory: 256Mi
            limits:
              cpu: 500m
              memory: 512Mi
