apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-pvc
  namespace: shoptech
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: managed-csi   # clase de almacenamiento por defecto en AKS
  resources:
    requests:
      storage: 5Gi
